### ISSUE TITLE
Severe vulnerability - CHF length extension attack + pickle

### ISSUE THREAD

**Issue by cdunklau** [rritoch/pandas_zmq#1]
https://github.com/rritoch/pandas_zmq/blob/0af2284b1fac93432ebce0a7d9a2fd12ed0c2d2f/pandas_zmq/_zmq.py#L19-L31

This code is almost certainly vulnerable to the classic [length-extension attack](https://en.wikipedia.org/wiki/Length_extension_attack) that most CHFs are susceptible to when used in this way. An attacker need only see an accepted hash + message (not the secret) to be able to reconstruct the hash function's state, and append arbitrary bytes and send a reconstructed hash that will be accepted by the receiver. Since pickle allows for arbitrary code execution, this winds up being a severe security hole.

Proper usage of [HMAC](https://docs.python.org/3/library/hmac.html) instead of a CHF (e.g. SHA2) could mitigate this threat, but the whole concept of using pickle to send over the network is fraught with danger, so it would be much better to avoid that entirely. You could use a non-executable serialization format instead, such as HDF5 or something else [that pandas offers](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html).

**Comment by rritoch** [comment]
The length of the secret isn't known so this security vulnerability never existed BUT I have implemented a more secure hash algorithm in version 0.0.3 which is arguably more secure than HMAC.

**Comment by cdunklau** [comment]
The length of the secret is entirely irrelevant for a length extension attack. Given secret `s`, original message `m`, and appended data `a`, an attacker need not know anything about `s` to be able to compute `hash(s + m + a)`. They only need to know `hash(s + m)` and `m` itself, which is in the payload of the network stream.
